@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
@FieldsAreNonnullByDefault
@TypeParametersAreNonnullByDefault
@TypeUsesAreNonnullByDefault
package com.ultreon.craft.debug;

import com.ultreon.craft.FieldsAreNonnullByDefault;
import com.ultreon.craft.MethodsReturnNonnullByDefault;
import com.ultreon.craft.TypeParametersAreNonnullByDefault;
import com.ultreon.craft.TypeUsesAreNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;