@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
@FieldsAreNonnullByDefault
@TypeParametersAreNonnullByDefault
@TypeUsesAreNonnullByDefault
package com.ultreon.craft;

import javax.annotation.ParametersAreNonnullByDefault;