package com.ultreon.craft.client.render;

import org.lwjgl.opengl.GL30;

public enum DestinationBlending {
    ONE(GL30.GL_ONE),
    ZERO(GL30.GL_ZERO),
    SRC_COLOR(GL30.GL_SRC_COLOR),
    ONE_MINUS_SRC_COLOR(GL30.GL_ONE_MINUS_SRC_COLOR),
    DST_COLOR(GL30.GL_DST_COLOR),
    ONE_MINUS_DST_COLOR(GL30.GL_ONE_MINUS_DST_COLOR),
    SRC_ALPHA(GL30.GL_SRC_ALPHA),
    ONE_MINUS_SRC_ALPHA(GL30.GL_ONE_MINUS_SRC_ALPHA),
    DST_ALPHA(GL30.GL_DST_ALPHA),
    ONE_MINUS_DST_ALPHA(GL30.GL_ONE_MINUS_DST_ALPHA),
    CONSTANT_COLOR(GL30.GL_CONSTANT_COLOR),
    ONE_MINUS_CONSTANT_COLOR(GL30.GL_ONE_MINUS_CONSTANT_COLOR),
    CONSTANT_ALPHA(GL30.GL_CONSTANT_ALPHA),
    ONE_MINUS_CONSTANT_ALPHA(GL30.GL_ONE_MINUS_CONSTANT_ALPHA),
    SRC_ALPHA_SATURATE(GL30.GL_SRC_ALPHA_SATURATE);
    public final int id;

    DestinationBlending(int id) {
        this.id = id;
    }
}
